version = 0.1
[default.deploy.parameters]
stack_name = "cs147backend"
resolve_s3 = true
s3_prefix = "cs147backend"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
