AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  ExpressApi:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Events:
        AnyRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        AnyTempReadings:
          Type: Api
          Properties:
            Path: /temp-readings
            Method: ANY